json.array! @warehouses,
            :id,
            :name,
            :code,
            :description,
            :address,
            :city,
            :state,
            :postal_code,
            :total_area,
            :useful_area
