json.id @warehouse.id
json.name @warehouse.name
json.code @warehouse.code
json.description @warehouse.description
json.description @warehouse.address
json.city @warehouse.city
json.state @warehouse.state
json.postal_code @warehouse.postal_code
json.total_area @warehouse.total_area
json.useful_area @warehouse.useful_area
